# Generated by Django 4.2.29 on 2026-04-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_percentage', models.FloatField(default=5.0, help_text='% of bill earned as points')),
                ('point_value', models.FloatField(default=1.0, help_text='1 point = Rs X')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
    ]
