# Generated by Django 5.2 on 2026-04-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafelocation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
