# Generated by Django 5.2 on 2026-05-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_cafelocation_address_cafelocation_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cafelocation',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafe_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='branch_name',
            field=models.CharField(default='Main Branch', max_length=100),
        ),
        migrations.AddField(
            model_name='cafelocation',
            name='restaurant_name',
            field=models.CharField(default='My Cafe', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cafelocation',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('admin', 'table_number')},
        ),
    ]
