# Generated by Django 4.2.29 on 2026-05-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_cafelocation_admin_cafelocation_branch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafelocation',
            name='name',
        ),
    ]
