# Generated by Django 5.2 on 2026-05-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_admin_menuitem_admin_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Optional discount percentage (e.g. 20 for 20%)', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price after discount. Can be manually entered or auto-calculated.', max_digits=10, null=True),
        ),
    ]
