# Generated by Django 4.2.29 on 2026-05-15 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_menuitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='disabled_by_branches',
            field=models.ManyToManyField(blank=True, related_name='disabled_global_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='disabled_by_branches',
            field=models.ManyToManyField(blank=True, related_name='disabled_global_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
