# Generated by Django 4.2.29 on 2026-05-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_disabled_by_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='disabled_by_branches',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='disabled_by_branches',
        ),
    ]
