# Generated by Django 5.2 on 2026-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_sent', 'Order Sent'), ('order_received', 'Order Received'), ('order_served', 'Order Served'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('paid_by_points', 'Paid by Points')], default='order_sent', max_length=20),
        ),
    ]
